import { Router } from "express";
import { adminRouter } from "./admin.routes";
import { apartmentRouter } from "./apartment.routes";
import { announcementRouter } from "./announcement.routes";
import { assetCategoryRouter } from "./asset-category.routes";
import { assetRouter } from "./asset.routes";
import { feedbackCategoryRouter } from "./feedback-category.routes";
import { feedbackRecordRouter } from "./feedback-record.routes";
import { authRouter } from "./auth.routes";
import { bankAccountRouter } from "./bank-account.routes";
import { bankMatchingRuleRouter } from "./bank-matching-rule.routes";
import { bankTransactionRouter } from "./bank-transaction.routes";
import { buildingRouter } from "./building.routes";
import { communicationRouter } from "./communication.routes";
import { dashboardRouter } from "./dashboard.routes";
import { whatsappIntegrationRouter } from "./whatsapp-integration.routes";
import { whatsappWebhookRouter } from "./whatsapp-webhook.routes";
import { debtRouter } from "./debt.routes";
import { duesRouter } from "./dues.routes";
import { employeeRouter } from "./employee.routes";
import { expenseRouter } from "./expense.routes";
import { expenseTypeRouter } from "./expense-type.routes";
import { healthRouter } from "./health.routes";
import { paymentRouter } from "./payment.routes";
import { personRouter } from "./person.routes";
import { relationRouter } from "./relation.routes";
import { siteRouter } from "./site.routes";
import { subscriptionRouter } from "./subscription.routes";
import { siteSetupRouter } from "./site-setup.routes";
import { supplierRouter } from "./supplier.routes";
import { visitRouter } from "./visit.routes";
import { visitorRouter } from "./visitor.routes";
import { tenantUserRouter } from "./tenant-users.routes";

export const apiRouter = Router();

/** Lisans kilidi (requireValidLicense) bu fazda tenant route'larına takılmaz. */
apiRouter.use("/tenant-users", tenantUserRouter);
apiRouter.use("/admin", adminRouter);
apiRouter.use("/health", healthRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/sites", siteRouter);
apiRouter.use("/site-setup", siteSetupRouter);
apiRouter.use("/buildings", buildingRouter);
apiRouter.use("/apartments", apartmentRouter);
apiRouter.use("/persons", personRouter);
apiRouter.use("/apartment-person-relations", relationRouter);
apiRouter.use("/dues-definitions", duesRouter);
apiRouter.use("/apartment-debts", debtRouter);
apiRouter.use("/payments", paymentRouter);
apiRouter.use("/expenses", expenseRouter);
apiRouter.use("/expense-types", expenseTypeRouter);
apiRouter.use("/suppliers", supplierRouter);
apiRouter.use("/employees", employeeRouter);
apiRouter.use("/visitors", visitorRouter);
apiRouter.use("/visits", visitRouter);
apiRouter.use("/bank-accounts", bankAccountRouter);
apiRouter.use("/bank-transactions", bankTransactionRouter);
apiRouter.use("/bank-matching-rules", bankMatchingRuleRouter);
apiRouter.use("/asset-categories", assetCategoryRouter);
apiRouter.use("/assets", assetRouter);
apiRouter.use("/announcements", announcementRouter);
apiRouter.use("/feedback-categories", feedbackCategoryRouter);
apiRouter.use("/feedback-records", feedbackRecordRouter);
apiRouter.use("/communications", communicationRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/subscription", subscriptionRouter);
apiRouter.use("/integrations/whatsapp", whatsappIntegrationRouter);
apiRouter.use("/webhooks/whatsapp", whatsappWebhookRouter);
