/** Merkezi finansal güvenlik kontrol kodları. */

export const FinanceIssueSeverity = {
  INFO: "INFO",
  WARNING: "WARNING",
  BLOCK: "BLOCK",
} as const;

export type FinanceIssueSeverity =
  (typeof FinanceIssueSeverity)[keyof typeof FinanceIssueSeverity];

export const FinanceIssueCode = {
  APARTMENT_NOT_FOUND: "APARTMENT_NOT_FOUND",
  APARTMENT_INACTIVE: "APARTMENT_INACTIVE",
  NO_OPEN_DEBT: "NO_OPEN_DEBT",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  OVERPAYMENT_NO_CREDIT: "OVERPAYMENT_NO_CREDIT",
  DEBT_ALREADY_PAID: "DEBT_ALREADY_PAID",
  DEBT_NOT_OPEN: "DEBT_NOT_OPEN",
  DEBT_ALLOCATION_OVERFLOW: "DEBT_ALLOCATION_OVERFLOW",
  ALLOCATION_SUM_MISMATCH: "ALLOCATION_SUM_MISMATCH",
  DUPLICATE_PAYMENT_EXACT: "DUPLICATE_PAYMENT_EXACT",
  DUPLICATE_PAYMENT_SUSPECTED: "DUPLICATE_PAYMENT_SUSPECTED",
  BANK_TX_ALREADY_PROCESSED: "BANK_TX_ALREADY_PROCESSED",
  BANK_TX_NOT_CREDIT: "BANK_TX_NOT_CREDIT",
  BANK_TX_INACTIVE: "BANK_TX_INACTIVE",
  BANK_TX_NO_APARTMENT: "BANK_TX_NO_APARTMENT",
  BALANCE_CHANGED_SINCE_PREVIEW: "BALANCE_CHANGED_SINCE_PREVIEW",
  PAYMENT_ALREADY_CANCELLED: "PAYMENT_ALREADY_CANCELLED",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  DUES_ALL_PERIODS_EXIST: "DUES_ALL_PERIODS_EXIST",
  DUES_PERIOD_CONFLICT: "DUES_PERIOD_CONFLICT",
  DUES_AMOUNT_DIFFERS: "DUES_AMOUNT_DIFFERS",
  MULTI_PERIOD_ALLOCATION: "MULTI_PERIOD_ALLOCATION",
  CANCEL_IMPACT: "CANCEL_IMPACT",
} as const;

export type FinanceIssueCode = (typeof FinanceIssueCode)[keyof typeof FinanceIssueCode];

/** WARNING kodları — yalnız bunlar onaylanarak geçilebilir. */
export const CONFIRMABLE_WARNING_CODES: ReadonlySet<FinanceIssueCode> = new Set([
  FinanceIssueCode.DUPLICATE_PAYMENT_SUSPECTED,
  FinanceIssueCode.DUES_AMOUNT_DIFFERS,
]);
